### ISSUE TITLE
windows 7 64bit Installation error

### ISSUE THREAD

**Issue by msenturk** [tvdburgt/subtle#1]
![error](https://i.imgur.com/9BmyEuB.png)

**Comment by tvdburgt** [comment]
Do you have [.NET 4.5.2](https://www.microsoft.com/en-us/download/details.aspx?id=42642)? If this fixes the problem, I can update the installer accordingly.

**Comment by msenturk** [comment]
after updating from 4.5.1 to 4.5.2 solved the problem.
