### ISSUE TITLE
CLI & UI: Please add multiple download

### ISSUE THREAD

**Issue by sniper-developer** [tvdburgt/subtle#11]
Please add possibility to select multiple found subs in UI and download them all.
-naming for subs aftet 1st one can be *.2.srt, *.3.srt etc.
-ignore "cannot download error message" if more than 1 is selected and at least one was downloaded.
-same functionality for CLI: just flag like --dl-all to switch download of 1st found and all found.
Thank you in advance!

**Comment by tvdburgt** [comment]
I don't think I like this suggestion. It's not very intuitive and I can't think of a *good* use case. In what order should the subs be named in case of multiple selection?

**Comment by sniper-developer** [comment]
They should be named in same order they are sorted now )
(Another useful request here, is to add sorting by column by pressing on column header, but I will use cli since it's working now ))

As for the topic: it is very useful: I download many subs for TV series, usually on release day. There are often bad subtitles with different timings or just bad translations. And they can also appear at the top of the list.
If several are downloaded, I just quick-switch in player to next one(single key press) and see how it fits.
It also kinda fixes "cannot download error message", because, well, something will be still downloaded. And this message appears on 1st sub in the list sometimes too. (that's another issue, but i've accidentally deleted TV episodes with reproduce, will report later if reappear).

**Comment by musahi0128** [comment]
Yo,

I hope this get implemented :)

**Comment by tvdburgt** [comment]
I want to keep the GUI as clean and easy to use as possible. Reserving this functionality for command-line only.

**Comment by andradadad** [comment]
Any update on this for the command-line only?

**Comment by tvdburgt** [comment]
I'll try to have a look at this the coming weekend.

**Comment by andradadad** [comment]
The multi-language download would be a great feature since subtle downloads faster than other software, but sadly replaces the .srt
