### ISSUE TITLE
Bug: searches old subtitle

### ISSUE THREAD

**Issue by sniper-developer** [tvdburgt/subtle#14]
Please take a look at the image.
Not sure, maybe it's bug in opensubtitles API, but if so, my other request to DL several subs becomes even more needed.
Currently CLI downloads just 1st one in the list.
![subtle 2016-05-04 23 18 29](https://cloud.githubusercontent.com/assets/10760181/15027990/26a1ce70-124f-11e6-821b-c5a05b9eff0e.jpg)

**Comment by tvdburgt** [comment]
This most likely a user error by the uploader (using the wrong file hash or incorrect subtitle name). If this is the case, just give the sub a bad rating so it doesn't stay at the top.

**Comment by sniper-developer** [comment]
Well, this happens A LOT, like every 3rd episode (of any series, i watch a lot of them apparently )).
Solution for cli: add flag to sort by date or set minimum date threshhold (for example, "-d 2" means subtitles not older than 2 days).
Another solution can be to additionally check actual name, even if hash seems to match. maybe with additional flag --force_name_match

**Comment by sniper-developer** [comment]
Just to add: i've changed ordering to date, like this:
private static Subtitle SelectSubtitle(IEnumerable<Subtitle> subs)
{
    return subs.OrderByDescending(s => s.UploadDate)...

And so far, no issues for 10 days (each day ~2 different episodes).
