### ISSUE TITLE
401 Unauthorized and JIT Debugging

### ISSUE THREAD

**Issue by redebs** [tvdburgt/subtle#15]
Hi! I got this error when I first launched subtle.exe:

> See the end of this message for details on invoking 
> just-in-time (JIT) debugging instead of this dialog box.

*************\* Exception Text **************
CookComputing.XmlRpc.XmlRpcServerException: Backend fetch failed
   at CookComputing.XmlRpc.XmlRpcClientProtocol.ReadResponse(XmlRpcRequest req, WebResponse webResp, Stream respStm)
   at CookComputing.XmlRpc.XmlRpcClientProtocol.EndInvoke(IAsyncResult asr, Type returnType)
   at XmlRpcProxy3e8002bd-8633-4811-aedb-b44f58c938b3.EndLogIn(IAsyncResult )
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)

*************\* Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
##     CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll

subtle
    Assembly Version: 1.0.0.0
    Win32 Version: 0.4
##     CodeBase: file:///C:/Program%20Files%20(x86)/Subtle/subtle.exe

Subtle.Model
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
##     CodeBase: file:///C:/Program%20Files%20(x86)/Subtle/Subtle.Model.DLL

System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll

System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll

System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll

Octokit
    Assembly Version: 0.17.0.0
    Win32 Version: 0.17.0
##     CodeBase: file:///C:/Program%20Files%20(x86)/Subtle/Octokit.DLL

AutoMapper
    Assembly Version: 4.0.4.0
    Win32 Version: 4.0.4.0
##     CodeBase: file:///C:/Program%20Files%20(x86)/Subtle/AutoMapper.DLL

System.Net.Http
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll

CookComputing.XmlRpcV2
    Assembly Version: 3.0.0.0
    Win32 Version: 3.0.0.266
##     CodeBase: file:///C:/Program%20Files%20(x86)/Subtle/CookComputing.XmlRpcV2.DLL

XmlRpcProxy3e8002bd-8633-4811-aedb-b44f58c938b3
    Assembly Version: 0.0.0.0
    Win32 Version: 3.0.0.266
##     CodeBase: file:///C:/Program%20Files%20(x86)/Subtle/CookComputing.XmlRpcV2.dll

System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll

System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll

System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll

System.Security
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Security/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Security.dll

Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll

*************\* JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

`<configuration>`
   `<system.windows.forms jitDebugging="true" />`
`</configuration>`

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

> ---

I have tried to edit the subtle.exe.config and/or machine.config to add the code but this results in the program not working completely, or even opening, for that matter. I only get the generic Send Information error from Windows. 

When I don't touch the.config files, I get the error "401 unauthorized" when I launch subtle.exe and can't do anything in the program.

Running a fresh-installed Windows 7 Home without Visual Studio.

**Comment by tvdburgt** [comment]
Seems related to #13 (server error). I will improve error handling on this issue, so the exception is less of a nuisance.

**Comment by tvdburgt** [comment]
This is resolved in v0.4.2.
