### ISSUE TITLE
401 Unathorized error

### ISSUE THREAD

**Issue by jathri** [tvdburgt/subtle#17]
Used to work good but not anymore. See:
`https://i.imgur.com/z6p2kYx.jpg`
Can you please help?

**Comment by tvdburgt** [comment]
This is caused by the opensubtitles.org backend (see #15 et al). Did you reach your daily subtitle download quota (I believe it's 100)?

**Comment by j-t-r2** [comment]
I suppose this wont help, right?
System.InvalidOperationException: Session is not initialized
   v Subtle.Model.OSDbClient.CheckSession()
   v Subtle.Model.OSDbClient.<SearchSubtitlesAsync>d__10.MoveNext()

   v System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   v System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   v Subtle.Gui.MainForm.<SearchSubtitles>d__12.MoveNext()

   v System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   v System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   v Subtle.Gui.MainForm.<SearchSubtitles>d__14.MoveNext()

   v System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   v System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   v Subtle.Gui.MainForm.<LoadFile>d__10.MoveNext()

   v System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)

**Comment by j-t-r2** [comment]
Did you reach your daily subtitle download quota (I believe it's 100)?
> I am on shared IP so that can be a case. But your app have worked flawlessly until recently, on the other hand.

**Comment by tvdburgt** [comment]
Is this issue persistent? Or does it only happen sporadically? In Subtle's menu bar > Help > About, you can see your subtitle quota.
