### ISSUE TITLE
No Context menu for MKV files

### ISSUE THREAD

**Issue by Titousky** [tvdburgt/subtle#22]
There is no context menu shortcut when I right click on MKV files.

**Comment by fabionar** [comment]
I'm having the same issue on windows 7. Both 64bit and 32.

**Comment by tvdburgt** [comment]
I don't have access to a Windows 7 machine, so I can't verify this unfortunately. Do other video file types work? You could try and play around with the values in the `HKEY_CLASSES_ROOT\SystemFileAssociations` registry tree. Windows support for custom file type associations is really crappy and there is literally no up-to-date support...

**Comment by Titousky** [comment]
Now it's working for me n Windows 10, though I didn't do anything.
Best subtitle soft ever btw !
