### ISSUE TITLE
Trojan?

### ISSUE THREAD

**Issue by mafhper** [tvdburgt/subtle#23]
![01](https://user-images.githubusercontent.com/563991/35187389-4fa74072-fe0a-11e7-843e-d0553424d3ee.jpg)

**Comment by mafhper** [comment]
There´s a serious problem here.  [https://www.virustotal.com/pt/file/ba4f35303cdd4eb90b8120f431b9d04810def1b8e436f02893d9929404562355/analysis/1516452664/](url)

**Comment by zaggynl** [comment]
https://www.virustotal.com/#/file/ba4f35303cdd4eb90b8120f431b9d04810def1b8e436f02893d9929404562355/detection

@tvdburgt : please advice if this is a false positive or not!

**Comment by tvdburgt** [comment]
This is a false positive.
