### ISSUE TITLE
Subscene Support

### ISSUE THREAD

**Issue by ghost1372** [tvdburgt/subtle#4]
hi can you please add Subscene as source? opensubtitle is not fully active. it is good only for english subtitles. subscene is very active and support alot of language.
http://subscene.com/

and here is a good sample work with subscene.com ,i couldnt compile it.
https://github.com/crashh/Subtitle-Downloader
tnx

**Comment by tvdburgt** [comment]
Subscene support would be nice, but I'm not sure if they provide a public API? It seems your example scrapes the website itself, which isn't very efficient and might not be legal..?

**Comment by tvdburgt** [comment]
Closing this issue because Subscene doesn't seem to offer a service for searching/downloading subtitles.
