### ISSUE TITLE
cli fails with "Input string was not in a correct format."

### ISSUE THREAD

**Issue by sniper-developer** [tvdburgt/subtle#7]
In different countries, decimal point format differs.
Please change code, for example like this:

        private static SubtitleSearchResult SelectSubtitle(IEnumerable<SubtitleSearchResult> subs)
        {
            return subs
                .OrderByDescending(s => int.Parse(s.IsFeatured))
                .ThenByDescending(s => decimal.Parse(s.Rating, System.Globalization.CultureInfo.InvariantCulture))
>>> ---     .ThenByDescending(s => int.Parse(s.DownloadCount))
>>> +++   .ThenByDescending(s => decimal.Parse(s.Rating, System.Globalization.CultureInfo.InvariantCulture))

                .FirstOrDefault();
        }

**Comment by tvdburgt** [comment]
This should be fixed in 0.4.1. Please verify and close this issue. Thanks!

**Comment by sniper-developer** [comment]
Fixed, thank you!
