### ISSUE TITLE
cli is not downloading files

### ISSUE THREAD

**Issue by sniper-developer** [tvdburgt/subtle#9]
Actually, cli version finds subs but doesn't download srt.
I tried debugging, but VS always detaches and application ends somewhere around
var downloads = await client.DownloadSubtitlesAsync(subs.Select(s => s.Selection.Id).ToArray());
Unfortunately, I'm not C# programmer myself, but I can provide some other info on request, if not reproduced.

**Comment by tvdburgt** [comment]
Does this still occur in the latest version? Is this related to #7?

**Comment by sniper-developer** [comment]
Fixed, thank you!
